spring:
  application:
    name: comment-service
  kafka:
    bootstrap-servers: localhost:9092
    topic: comment-create
  jpa:
    hibernate:
      ddl-auto: validate
    liquibase:
      change-log: classpath:db/changelog-master.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/test_jdbc
    username: root
    password: azizkhan
server:
  port: 8083
jwt:
  secret: ENk2InMhEpe50LtIdvnjbjE0Ia0virEr9wCJJ6UAms


